### PR TITLE
Move everything into git, so it's easy to package

### PR DESCRIPTION
**Pull request by es20490446e**
Currently there is no easy way to package GeneralUser-GS into Linux because:

- The Google Drive link asks to manually confirm download.

- The GeneralUser-GS website is pure JavaScript. You cannot fetch the link, or any other info on it.

My suggestion is:

- Moving everything into GitHub, so packages can retrieve the download link and version automatically without having to manually keep inspecting new versions or having to modify the package recipe.

- Putting into the readme.md only the link to the website, so it's highly noticeable. Hence people are still strongly encouraged to visit the website and inform themselves about the software, the author, and the possibility to donate.

### CODE REVIEW

**Comment by mrbumpy409** [comment]
Thanks for the idea, Alberto! I agree with the need for a convenient packaging source. I will be incorporating most of your ideas in version 2.0.1, which I am preparing at the moment.

**Comment by es20490446e** [comment]
Oki. Shall I delete my fork now then?

**Comment by mrbumpy409** [comment]
> Oki. Shall I delete my fork now then?

Yes. I have just published 2.0.1, and the SF2 and support files are now in the GitHub repository. Thanks again!

**Comment by es20490446e** [comment]
Thanks to you! 🏆

**Pull request closed without merging**
